dataset_params:
  train_dir: ../datasets/VoxCeleb/train
  test_dir: ../datasets/VoxCeleb/test
  cpk_path: 'checkpoints/hdac.pth.tar'
  frame_shape: [256, 256, 3]
  num_sources: 2
  target_delta: 1 #maximum difference between the target frames
  base_layer: True 
  base_layer_params:
    bl_codec: 'hevc' # Base layer codec ['hevc', 'vvc']
    dir: ../datasets/VoxCeleb/ #path to bl data repositories labelled <CODEC_NAME>_bl
    variable_quality: True #Randomly sample difference base layer qualities at training time
    qp_values: {'50': {'lmbda': 1.1,'bitrate': 8},'48': {'lmbda': 1.4,'bitrate': 12}, '46': {'lmbda': 2.0,'bitrate': 18}, '44': {'lmbda': 2.8,'bitrate': 20}}
  augmentation_params:
    flip_param:
      horizontal_flip: False
      time_flip: False
    jitter_param:
      brightness: 0.1
      contrast: 0.1
      saturation: 0.1
      hue: 0.1

model_params:
  common_params:
    num_kp: 10
    num_channels: 3
  kp_detector_params:
    temperature: 0.1
    block_expansion: 32
    max_features: 1024
    scale_factor: 0.25
    num_blocks: 5
    quantize: False
  generator_params:
    block_expansion: 64
    max_features: 512
    num_down_blocks: 2
    num_bottleneck_blocks: 6
    estimate_occlusion_map: True
    ref_coder: True
    dense_motion_params:
      block_expansion: 64
      max_features: 1024
      num_blocks: 5
      scale_factor: 0.25
    iframe_params:
      variable_bitrate: True
      levels: 7
      scale_factor: 1
      input_resolution: [256,256]
  discriminator_params:
    scales: [1]
    block_expansion: 32
    max_features: 512
    num_blocks: 4
    use_kp: True
    disc_type: 'multi_scale' #'multi_scale' #patch_gan_disc

train_params:
  num_epochs: 100
  num_repeats: 1
  epoch_milestones: []
  lr: 2.0e-4
  lr_discriminator: 2.0e-4
  batch_size: 2
  scales: [1, 0.5, 0.25, 0.125]
  checkpoint_freq: 1
  transform_params:
    sigma_affine: 0.05
    sigma_tps: 0.005
    points_tps: 5
  loss_weights:
    generator_gan: 1
    discriminator_gan: 1
    feature_matching: [10, 10, 10, 10]
    perceptual: [10, 10, 10, 10, 10]
    equivariance_value: 10
    equivariance_jacobian: 10
    mse_loss: 100

visualizer_params:
  kp_size: 5
  draw_border: True
  colormap: "gist_rainbow"

eval_params: 
  qp: 6 #QPS [1-6]
  metrics: ['lpips','ms_ssim','dists','msVGG', 'fsim', 'psnr','vmaf']
  num_frames: 250
  gop_size: 250
  base_layer_qp: 50 #[50,45,40,35] #Base layer Frame quality [51 is lowest for HEVC]
  fps: 25
  per_frame_metrics: False
