dataset_params:
  train_dir: datasets/train
  test_dir: datasets/test
  frame_shape: [256, 256, 3]
  num_sources: 2
  target_delta: 2
  augmentation_params:
    flip_param:
      horizontal_flip: True
      time_flip: True
    jitter_param:
      brightness: 0.1
      contrast: 0.1
      saturation: 0.1
      hue: 0.1

model_params:
  common_params:
    num_kp: 10
    num_channels: 3
    estimate_jacobian: False
  kp_detector_params:
    temperature: 0.1
    block_expansion: 32
    max_features: 1024
    scale_factor: 0.25
    num_blocks: 5
  generator_params:
    block_expansion: 64
    max_features: 512
    num_down_blocks: 2
    num_bottleneck_blocks: 6
    estimate_occlusion_map: True
    dense_motion_params:
      block_expansion: 64
      max_features: 1024
      num_blocks: 5
      scale_factor: 0.25      

  discriminator_params:
    scales: [1]
    block_expansion: 32
    max_features: 512
    num_blocks: 4
    use_kp: True

train_params:
  num_epochs: 50
  num_repeats: 5
  epoch_milestones: []
  lr: 2.0e-4
  lr_discriminator: 2.0e-4
  batch_size: 36
  scales: [1, 0.5, 0.25, 0.125]
  checkpoint_freq: 10
  step_wise: False
  adversarial_training: True
  transform_params:
    sigma_affine: 0.05
    sigma_tps: 0.005
    points_tps: 5
  loss_weights:
    generator_gan: 1
    discriminator_gan: 1
    feature_matching: [10, 10, 10, 10]
    perceptual: [10, 10, 10, 10, 10]
    equivariance_value: 10
    equivariance_jacobian: 10

visualizer_params:
  kp_size: 5
  draw_border: True
  colormap: "gist_rainbow"

eval_params:
  ref_codec: 'ai' #BPG codec is now deprecated :: We use Cheng2020 LIC from compressai
  qp: 4 #QPS [1-6]
  #evaluation metrics: Other implemented metrics ['psnr-hvs', 'nlpd', 'iw_ssim','vif']
  metrics: ['lpips','dists','msVGG', 'fsim', 'ms_ssim', 'psnr','vmaf']
  temporal: False # Set to store per frame reconstruction quality in the output file
  num_frames: 128 #number of frames to animate from a single reference in the test videos
  gop_size: 32 #number of frames to animate from 1 reference = gop_size-1
  rd_point: 0 #
  fps: 20 #frames-per-second for bitrate computation