dataset_params:
  train_dir: datasets/train
  test_dir: datasets/test
  base_layer_dir: datasets/hevc
  frame_shape: [256, 256, 3]
  base_layer: True
  num_sources: 2
  augmentation_params:
    flip_param:
      horizontal_flip: False
      time_flip: False
    jitter_param:
      brightness: 0.1
      contrast: 0.1
      saturation: 0.1
      hue: 0.1

model_params:
  common_params:
    num_kp: 10
    num_channels: 3
    estimate_jacobian: False
  kp_detector_params:
    temperature: 0.1
    block_expansion: 32
    max_features: 1024
    scale_factor: 0.25
    num_blocks: 5
    quantize: True
  generator_params:
    block_expansion: 64
    max_features: 512
    num_down_blocks: 2
    num_bottleneck_blocks: 6
    estimate_occlusion_map: True
    residual_features: 12
    dense_motion_params:
      block_expansion: 64
      max_features: 1024
      num_blocks: 5
      scale_factor: 0.25

  discriminator_params:
    scales: [1]
    block_expansion: 32
    max_features: 512
    num_blocks: 4
    use_kp: True

train_params:
  num_epochs: 50
  num_repeats: 1
  epoch_milestones: []
  lr: 2.0e-4
  lr_discriminator: 2.0e-4
  batch_size: 3
  scales: [1, 0.5, 0.25, 0.125]
  checkpoint_freq: 10
  step_wise: False # set to true to train each component independently i.e. DAC -> HDAC | RDAC
  adversarial_training: True #Set to false to train with adversarial losses.
  transform_params:
    sigma_affine: 0.05
    sigma_tps: 0.005
    points_tps: 5
  loss_weights:
    generator_gan: 1
    discriminator_gan: 1
    feature_matching: [10, 10, 10, 10]
    perceptual: [10, 10, 10, 10, 10]
    equivariance_value: 10
    equivariance_jacobian: 10

eval_params:
  ref_codec: 'ai' #[ai] #to-do: reintegrate BPG codec.
  qp: 5 #AI_QPS [1-6]
  metrics: ['lpips', 'msVGG', 'fsim', 'ms_ssim', 'psnr', 'vmaf','dists']
  temporal: False #Metrics are stored as an average over the whole sequences. Set true to store per frame metrics
  num_frames: 32 #total number of frames to compress from the input video
  gop_size: 16 #number of frames to animate from a single reference in the test videos