dataset_params:
  root_dir: ../datasets/
  frame_shape: [256, 256, 3]
  base_layer: False
  num_sources: 3
  target_delta: 2
  use_saliency_map: False
  augmentation_params:
    flip_param:
      horizontal_flip: False
      time_flip: False
    jitter_param:
      brightness: 0.1
      contrast: 0.1
      saturation: 0.1
      hue: 0.1

model_params:
  common_params:
    num_kp: 10
    num_channels: 3
    estimate_jacobian: False
  kp_detector_params:
    temperature: 0.1
    block_expansion: 32
    max_features: 1024
    scale_factor: 0.25
    num_blocks: 5
    quantize: True
  generator_params:
    block_expansion: 64
    max_features: 512
    num_down_blocks: 2
    num_bottleneck_blocks: 6
    estimate_occlusion_map: True
    residual_features: 12
    dense_motion_params:
      block_expansion: 64
      max_features: 1024
      num_blocks: 5
      scale_factor: 0.25
    sdc_params:
      scale_factor: 1 #set to fraction to test if compression efficiecy is higher with lower dimension residuals
      num_intermediate_layers: 2 #upsampling/downsampling blocks in the compression VAE
    rec_network_params:
      gen_rec: False #Use convolutional network for reconstruction
      num_blocks: 4
    upsampler_params:
      upscale: False #Use convolutional network for reconstruction
      num_blocks: 4
      std: 0.05
      scale_factor: 1


  discriminator_params:
    scales: [1]
    block_expansion: 32
    max_features: 512
    num_blocks: 4
    use_kp: True

train_params:
  num_epochs: 50
  num_repeats: 1
  epoch_milestones: []
  lr: 2.0e-4
  lr_discriminator: 2.0e-4
  batch_size: 24
  scales: [1, 0.5, 0.25, 0.125]
  rd_lambda: [0.05,0.1,0.2,0.3,0.5,0.7,0.9,1.4]
  target_rate: 2
  sm_variance: 0.01
  sm_type: 'pretrained' # 'pretrained'-semantic KP from mediapipe or 'trainable'-unsupervised learned motion KPs
  checkpoint_freq: 10
  step_wise: True
  adversarial_training: False
  transform_params:
    sigma_affine: 0.05
    sigma_tps: 0.005
    points_tps: 5
  loss_weights:
    generator_gan: 1
    discriminator_gan: 1
    feature_matching: [10, 10, 10, 10]
    perceptual: [10, 10, 10, 10, 10]
    equivariance_value: 10
    equivariance_jacobian: 10

reconstruction_params:
  num_videos: 1000
  format: ".mp4"

animate_params:
  num_pairs: 50
  format: ".mp4"
  normalization_params:
    adapt_movement_scale: False
    use_relative_movement: True
    use_relative_jacobian: True

visualizer_params:
  kp_size: 3
  draw_border: True
  colormap: "gist_rainbow"
